### ISSUE TITLE
How to output only skull removal images?

### ISSUE THREAD

**Issue by GuoCHance** [WCHN/CTseg#15]

**Comment by brudfors** [comment]
Hello @GuoCHance 

If you want to output only the skull-stripped CT scan and nothing else, setting the `spm_CTseg` input arguments `tc` and `def` to false, and `skullstrip` to true should do the trick.

**Comment by GuoCHance** [comment]
> 

thanks a lot !! It works !
But unfortunately, I am still trying to solve the problem "Out of memory"...

**Comment by brudfors** [comment]
Great you got it working! CTseg can require quite a lot of RAM if your are working on large images. Depending on your aim, a possible solution could be to downsample the CT image by some amount (making sure that the downsampling is encoded in the affine matrix of the nifti header).

**Comment by GuoCHance** [comment]
> Great you got it working! CTseg can require quite a lot of RAM if your are working on large images. Depending on your aim, a possible solution could be to downsample the CT image by some amount (making sure that the downsampling is encoded in the affine matrix of the nifti header).

Thank you for your patient reply. I will try it !
