### ISSUE TITLE
Error using websave when running Docker in Windows

### ISSUE THREAD

**Issue by basicskywards** [WCHN/CTseg#22]
Firstly, thank you a lot for creating this useful tool for neuroimaging.

I'm using Docker to run CTseg on Windows.

Command use:
docker run --rm -it -v D:\Softwares\CTseg\data:/data ubuntu:ctseg function spm_CTseg '/data/CT.nii.gz'

Issue:
![image](https://user-images.githubusercontent.com/39130870/225250848-ad233068-08dd-49a6-85d5-03d9fc6b79b4.png)

It seems 'prior_CTseg.mat' and 'mu_CTseg.nii' cannot be downloaded automatically. So my quick solution is I downloaded it manually and saved to my local machine. And now I want to copy it to Docker container and deprecate the 'websave' function. 
But I hit some questions:

What location in Docker containter should it be copied to? 
And where can I find spm_CTseg.m so that i can remove websave?
Or could you please mind suggesting a better solution?

Thank you a lot again!

**Comment by gllmflndn** [comment]
Hello @basicskywards 
The issue probably took place when building the Docker image but this was hidden due to my commit 40e7bcc.
The dropbox link works for me so not sure what is going on here but if you did download the files manually and saved them in the same folder than `spm_CTseg.m` (i.e. the directory of this repo) then if you build the Docker image again, these files will be automatically copied in the image and `websave` shouldn't be called.

**Comment by basicskywards** [comment]
Hi @gllmflndn, 
I got it. I will save those files in the same folder as ```spm_CTseg.m``` and build the Docker image again. 
Thank you a lot for your suggestion!

**Comment by basicskywards** [comment]
Hi @gllmflndn , 

I put those files in the same folder as ```spm_CTseg.m``` like below 

![image](https://user-images.githubusercontent.com/39130870/225554046-51650937-1594-4bb8-946b-94165c704c10.png)

and then build the Docker image again from the beginning using ```docker build --no-cache -t ubuntu5:ctseg5 -f CTseg/Dockerfile .```. It finished successfully like below
![image](https://user-images.githubusercontent.com/39130870/225555344-727ff9fe-4b16-4266-b24e-216e99bcb3ec.png)

Unfortunately, when i run ```docker run --rm -it -v D:\Softwares\CTseg_new\data:/data ubuntu5:ctseg5 function spm_CTseg '/data/CT.nii.gz'``, i still hit the same issue.

![image](https://user-images.githubusercontent.com/39130870/225554931-a171676a-7183-455f-84b1-1f333d3a2b83.png)

Could you please mind helping with this issue?
Thank you a lot!

**Comment by gllmflndn** [comment]
Hi @basicskywards 
Sorry, I had forgotten how CTseg's Dockerfile was written and there was no chance my suggestion would have worked here. One solution would be to add a `COPY` instruction in the Dockerfile to copy the files at their right place in the container but I'm also going to make a new compiled version of SPM+CTseg that will natively contain these files - it might take me a bit of time but I'll let you know when it is available.

**Comment by basicskywards** [comment]
Hi @gllmflndn

I got it! I will update my repo and build it again. 
Thank you so much for your kind support!

**Comment by gllmflndn** [comment]
The link might change but for now you should be able to pull a pre-built Docker image with:
```
docker run --rm -it -v dir_host:/data ghcr.io/spm/spm-docker:docker-tbx function spm_CTseg '/data/CT.nii'
```
(don't forget to replace `dir_host` with the name of the directory containing the NIfTI file `CT.nii`.

**Comment by basicskywards** [comment]
I re-built the Docker image with your updated commit and it worked now. 
Thank you a lot again @gllmflndn !
